### ISSUE TITLE
Document getting a time from parsedatetime into a standard Python structure

### ISSUE THREAD

**Issue by dellis23** [bear/parsedatetime#112]
It seems like most people will want some additional way to manipulate the information retrieved from `parsedatetime`.  It would be nice to have a simple example of how they can do that.

For instance:

```
In [11]: from time import mktime

In [12]: from datetime import datetime

In [14]: datetime.fromtimestamp(mktime(parsedatetime.Calendar().parse('4:30')[0]))
Out[14]: datetime.datetime(2015, 8, 4, 4, 30)
```

Let me know if you think this is valuable and I can whip something up for the readme in a more concise / readable format.

**Comment by bear** [comment]
I think this would be an excellent start to an examples or howto page/section

+1 sir

**Comment by dellis23** [comment]
Fixed by https://github.com/bear/parsedatetime/issues/113
