### ISSUE TITLE
Dates in the format 'YYYY-MM-DD HH:MM' give the incorrect month and day

### ISSUE THREAD

**Issue by dellis23** [bear/parsedatetime#114]
Perhaps I'm using the library wrong.  Is this intended to work?

```
In [7]: parsedatetime.Calendar().parse('2015-06-15 04:30')
Out[7]: ((2015, 8, 5, 4, 30, 0, 2, 217, 1), 2)
In [8]: parsedatetime.Calendar().parse('06-15-2015 04:30')
Out[8]: ((2015, 8, 5, 4, 30, 0, 2, 217, 1), 2)
```

It seems to have correctly parsed out the time, but the date is ignored.  The library works great with stuff like "2 hours ago", but it fails for this.

**Comment by bear** [comment]
technically we have tried to make it work with dates of that type, but it turns out to be a lot of messy work since the focus of the lib is about fuzzy/natural dates

**Comment by dellis23** [comment]
:+1: makes sense, thanks!

**Comment by idpaterson** [comment]
This actually is supported as of a couple weeks ago. If you need to parse this particular format, installing parsedatetime from the master branch should work. It does not support full ISO8601 dates (e.g. 2015-06-15T04:30:26-0500) but your example is a simpler format.
