### ISSUE TITLE
the pdt_locales/en_AU.py file uses en_A for the localID instead of en_AU

### ISSUE THREAD

**Issue by bear** [bear/parsedatetime#120]
A very old mistake that should be fixed - will require a major version bump

found during work on PR #118

**Comment by MatthiasKauer** [comment]
Why does this require a major version bump? In other words: In what situations should I expect things to break?
I'm trying to figure out if I should modify code in my project that depends on this one.

**Comment by bear** [comment]
@MatthiasKauer In hindsight I would agree with you - it didn't need a major version bump but I had already rolled it into the v2.0 changes 

to be honest the amount of bug fixes that have been made since then is more of a reason to upgrade

**Comment by MatthiasKauer** [comment]
Thanks for clarifying.
I'll update for sure. I'm mainly trying to figure out where I should look for things to possibly break in my own code with that upgrade.

**Comment by bear** [comment]
The CHANGES.txt log is very complete, but I realize may not have all of the info you need -- the vast majority of the changes are bug fixes and I don't think we made any changes to how methods are called or their return values.

thanks!

**Comment by MatthiasKauer** [comment]
I'm coming from that changes file. It is indeed very good. The reason I'm asking is that it lists this issue as sole reason for the major version increase. When I come here, however, it didn't feel so major at first glance. Anyhow, sorry to bother you and thanks for the explanation!

**Comment by bear** [comment]
glad to help and thanks for the suggestion - I will definitely be more aware of how the changes file reads to others going forward!
