### ISSUE TITLE
v2.0 release

### ISSUE THREAD

**Issue by bear** [bear/parsedatetime#121]
Given that this is a major version # release I wanted to give folks a chance to add anything they wanted to make sure got into this release.

Not sure how many folks read the google group for the project so I decided to add this issue and then "ping" everyone - sorry!

@philiptzou @idpaterson @geoffreyfloyd @thedrow @WarmongeR1 

if you do have something you want to make sure is in the release, create an issue and then reference this one - once all referenced issues are marked as closed I'll do the release.

thanks!

**Comment by WarmongeR1** [comment]
#122 
#119

**Comment by WarmongeR1** [comment]
#124

**Comment by WarmongeR1** [comment]
#125

**Comment by philiptzou** [comment]
#131

**Comment by philiptzou** [comment]
#132

**Comment by bear** [comment]
I pushed v2.0 out to fix the leap day issue found in Issue #155
