### ISSUE TITLE
Put locales into config-files (yaml)

### ISSUE THREAD

**Issue by WarmongeR1** [bear/parsedatetime#124]
I think locales in ```.py``` is bad practice, because locale is class with ONE method (```__init__```).

My suggestion: put locales into yaml-files.

**Comment by bear** [comment]
would locales then become parameters to the main call?
Can you work up what this would look like as a PR?

**Comment by WarmongeR1** [comment]
Ok, I write this code

**Comment by WarmongeR1** [comment]
I tried. There is no result. I will still try

**Comment by bear** [comment]
no worries - I appreciate you wanting to solve this

**Comment by philiptzou** [comment]
The yaml files will introduce new dependency to PyYAML. I don't like the new dependency (which means you had to compile PyYAML before pdt get installed).

**Comment by bear** [comment]
my thought about that would be to take the work of converting it to YAML and then see if that could be done as JSON.

another option would be to make the PyYAML part only something that would have to be done during the build process -- i.e. generate the data that would be used during normal pdt use by reading and processing the PyYAML

**Comment by WarmongeR1** [comment]
You can find my code in branch ```yaml_locales```

**Comment by bear** [comment]
thanks @WarmongeR1 !

**Comment by WarmongeR1** [comment]
@bear, in branch ```yaml_locales``` - many yaml files, but not all tests pass

**Comment by philiptzou** [comment]
@WarmongeR1 I agreed with your opinion that `.py` is bad practice. But whether YAML or JSON they all share two disadvantages that: unserialization reduces performance, and the flexibility is lower than `.py` files. So I'm thinking about other pure Python built-in solutions. Especially a few of `.py` files like Django `settings.py` but not using class. I'll write another version about this thought and let's discuss on these two solutions.

**Comment by bear** [comment]
@philiptzou - looking forward to a .py solution that covers the concern that @WarmongeR1 raised

**Comment by philiptzou** [comment]
I did the modification in #130 which based on @WarmongeR1's changes.

https://github.com/bear/parsedatetime/compare/yaml_locales...philiptzou:alt_locales

**Comment by WarmongeR1** [comment]
Sorry, now i have many works :(  I can't create full pull request with this feature. 
We can base on PR #130  by @philiptzou

**Comment by philiptzou** [comment]
@WarmongeR1 you can push it to your folk repository and you can create pull-request. It's a bit easier for us to review every lines you changed. Feel free to modify anything based on #130.

**Comment by bear** [comment]
blocking https://github.com/bear/parsedatetime/issues/121

**Comment by philiptzou** [comment]
@WarmongeR1 Will you add new changes for this issue? Or this issue is solved and can be closed?

**Comment by bear** [comment]
oh right, this may not be blocking v2 anymore - i'll remove it for now and we can add it back if needed
