### ISSUE TITLE
Remove extra files

### ISSUE THREAD

**Issue by WarmongeR1** [bear/parsedatetime#125]
Remove trash files or paste into wiki.

For example 

- pylint.html
- locale_date_grouping_notes.txt
- implementation_notes.txt

**Comment by bear** [comment]
those two .txt files have been around since I first created the project - I don't mind adding them to the manifest so they don't get included in the build but I would like to keep them. 

maybe I'll merge them into a history.txt or something

**Comment by bear** [comment]
all are removed or put into directories that can be ignored for distribution
