### ISSUE TITLE
"Unresolved attribute reference 'parse' for class 'object'... " in Pycharm IDE.

### ISSUE THREAD

**Issue by sbonnick** [bear/parsedatetime#126]
Error:
"Unresolved attribute reference 'parse' for class 'object'... " in Pycharm IDE.

Version:
parsedatetime-1.5

Code to reproduce:

        from time import mktime
        import parsedatetime
        from datetime import datetime

        cal = parsedatetime.Calendar()
        time_struct, parse_status = cal.parse("tomorrow")
        datetime.fromtimestamp(mktime(time_struct))

`cal.parse` -> cal is not being detects as class Calendar and instead as object, which of course has no definition parse. Not sure what exactly is causing this, but my guess would be due to Calendar() being embedded in the __init__.py file. 

I do not see this issue while importing any other python modules.

**Comment by bear** [comment]
what version of parsedatetime?

**Comment by sbonnick** [comment]
1.5

**Comment by bear** [comment]
oh - silly me - you had that in your description - sorry!

**Comment by sbonnick** [comment]
no problem ;)

**Comment by sbonnick** [comment]
after thought: the IDE could be getting confused if it believes it is returning a plain object. I've seen similar behavior on functions that return a class object OR a dictionary. due to returning two different types, the IDE thinks it will always return the first return type. IE:

    def test_def():
        dict_var = { "Key": "Value" }
        return dict_var or module.class()

IDE will always assume the above is returning a dictionary, so code-completion on the "class()" class will not be given. 

I doubt this is the issue, but maybe a pointer to whats causing the issue

**Comment by sbonnick** [comment]
looking at the code, I dont see why we could not jsut drop the "object" implementation:

    class Calendar(object):

to 

    class Calendar:

**Comment by bear** [comment]
if that solves this problem and the tests work, then yea let's get a PR for that going

**Comment by sbonnick** [comment]
mind adding me as a contributor so i can create one?

**Comment by sbonnick** [comment]
PR created

**Comment by philiptzou** [comment]
Well, I think there must be a better reason for why PyCharm raised this error than inheritance of `object`. This perhaps an upstream bug of PyCharm or most likely there's some misconfiguration. Anyway, install a PyCharm and reappear this issue should be the first step but not just drop the inheritance.

**Comment by philiptzou** [comment]
Well happy ending of this issue. See #128.
