### ISSUE TITLE
No check to determine if a date exists within the text passed to parse() function

### ISSUE THREAD

**Issue by thequbit** [bear/parsedatetime#13]
Example of operation:

Python 2.7.3 (default, Apr 20 2012, 22:39:59)
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import parsedatetime as pdt
>>> c = pdt.Constants()
>>> c.BirthdayEpoc = 80
>>> p = pdt.Calendar(c)
>>> print p.parse("Mary had a little lamb.")
((2014, 3, 1, 20, 53, 56, 6, 69, 1), 1)
>>> print p.parse("foo bar")
(time.struct_time(tm_year=2013, tm_mon=3, tm_mday=10, tm_hour=20, tm_min=54, tm_sec=6, tm_wday=6, tm_yday=69, tm_isdst=1), 0)
>>> print p.parse("March 12th, 2013")
((2013, 3, 12, 20, 54, 34, 6, 69, 1), 1)
>>>

This is a resubmit with more information, and a better understanding of the library's operation.  Previous issue was #48.

**Comment by bear** [comment]
This is now handled by the nlp() routine - it will return None if no meaningful date/time text is found and it will call parse() if it does find something.

marking as closed, if you have other questions or feel this is not solved please do re-open the issue.

thanks!

**Comment by thequbit** [comment]
Oh man, i think this was actually my very first issue I ever filed on a FOSS project ... how exciting to see it closed!

I'll give this a go this evening and report back.  Thanks so much for taking the time to close it!

**Comment by bear** [comment]
do let me know how you end up - I'm all for opening this issue again (or morphing it to a doc/readme issue)

my apologies for making your first issue be such a bad experience!

**Comment by thequbit** [comment]
@bear No worries!
