### ISSUE TITLE
Bug: "2015-01-01" is parsed as the current date.

### ISSUE THREAD

**Issue by flight16** [bear/parsedatetime#133]
Reproducer script:

    import parsedatetime 
    str_in="2015-01-01"
    cal = parsedatetime.Calendar()
    dt_out = cal.parseDT(datetimeString=str_in)[0]
    str_out = dt_out.strftime("%Y-%m-%d")
    print("in={0}, out={1}".format(str_in, str_out))

Output:

    in=2015-01-01, out=2015-10-19

In my case I'm parsing "YYYY-MM-DD HH:MM" strings.

**Comment by idpaterson** [comment]
This is working in the latest master branch; the referenced fix has not yet been released but it is possible to parse both the date and time in that format. Version 2.0 is in progress, until then I recommend using the master branch to pick up a lot of fixes from the past few months.
