### ISSUE TITLE
Why I see 2016 instead of 2015?

### ISSUE THREAD

**Issue by CosmaVito** [bear/parsedatetime#136]
I want to convert a date as a string into type date.
E.g: Oct 4 = ' 2015-10-04 00:00:00 '

I try this:
    import parsedatetime as pdt

    c = pdt.Constants()
    p = pdt.Calendar(c)
    f = '%Y-%m-%d %H:%M:%S'

    data_format = p.parseDT(date_time)  //In this case date_time= "Oct 4"
    print data_format[0].strftime(f) 

This code works, but strangely i see 2016 instead of 2015.
So I see this: ' 2016-10-04 00:00:00 '

**Comment by idpaterson** [comment]
There is an option on Constants that allows you to interpret all dates without a year as relative to the current year. The default behavior is to assume that a date prior to today's date is referring to the following year.

Simply set the `YearParseStyle` to zero if you need this alternate behavior:
```python
c.YearParseStyle = 0
```

See #99 for more details
