### ISSUE TITLE
testOffsetAfterNoon fails (FreeBSD, Python 2.7.3)

### ISSUE THREAD

**Issue by emaste** [bear/parsedatetime#14]
Revision 692168f4bd336efc07e7575dcde7012eaa1e2075

python run_tests.py 
...
======================================================================
FAIL: testOffsetAfterNoon (parsedatetime.tests.TestSimpleOffsets.test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tank/emaste/src/parsedatetime/parsedatetime/tests/TestSimpleOffsets.py", line 94, in testOffsetAfterNoon
    self.assertTrue(_compareResults(self.cal.parse('5 hours after 12pm',     start), (target, 2)))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 46 tests in 0.710s

FAILED (failures=1)

**Comment by bear** [comment]
We have made a lot of little cleanup fixes and also updated the tests -- such that I am going to close this as fixed, the test hasn't failed in this way for a while during my runs.

If this is still happening with the very latest code please do re-open the issue.
