### ISSUE TITLE
What is the second value returned by `parse`?

### ISSUE THREAD

**Issue by rohithpr** [bear/parsedatetime#143]
```
>>> c.parse('now')
(time.struct_time(tm_year=2015, tm_mon=11, tm_mday=10, tm_hour=19, tm_min=59, tm_sec=23, tm_wday=1, tm_yday=314, tm_isdst=0), 2)
>>> c.parse('hello')
(time.struct_time(tm_year=2015, tm_mon=11, tm_mday=10, tm_hour=19, tm_min=59, tm_sec=29, tm_wday=1, tm_yday=314, tm_isdst=0), 0)
```

I'm trying to figure out what the second value returned is (the `2` and the `0`). Clearly it has some significance but I couldn't find any mention of it in the docs.

**Comment by bear** [comment]
It describes what type of date was found, it's documented in the source:

https://github.com/bear/parsedatetime/blob/master/parsedatetime/__init__.py#L1772

Note that after 2.3 is released we will be using the new Context flag to pass that information back, and it's documented:

https://github.com/bear/parsedatetime/blob/master/parsedatetime/context.py#L51

**Comment by rohithpr** [comment]
Thanks a lot!
