### ISSUE TITLE
examples/README refers to nonexistent (deleted?) file

### ISSUE THREAD

**Issue by georgehank** [bear/parsedatetime#147]
with_pyicu.py doesn't exist (anymore?) but is listed in the README

**Comment by philiptzou** [comment]
I don't see _pyicu.py in current master branch README.rst file. Can you check the version you used?

**Comment by bear** [comment]
The README has been adjusted to explain how and why pyICU is needed for testing.

please re-open this issue if we really have mis-read your issue
