### ISSUE TITLE
Inconsistent return types (1.5 installed with pip into 3.4)

### ISSUE THREAD

**Issue by georgehank** [bear/parsedatetime#148]
Calendar.parse returns a tuple with the first element being either a tuple or a struct_time.  At first glance (and I haven't dug into the "documentation", and probably won't) there is no discernible reason for why that is, and for why it's not just a datetime.datetime (or dt.date, or dt.time) object.

Okay, I overcame my hate for epydoc dumps and... hmm, no mention of this in the "docs".  Apparently, it's supposed to be a struct_time always?

**Comment by philiptzou** [comment]
Won't fix in 1.5 but fixed in e08e663731feb1e5c2bc6a50a664fa0381a95559.

Please try installing new version from Github.
