### ISSUE TITLE
A date with numbers returns wrong date

### ISSUE THREAD

**Issue by jonathan-s** [bear/parsedatetime#154]
`cal.parseDT(datetimeString='2000-02-31')` returns `(datetime.datetime(2016, 2, 22, 20, 0), 2)` could perhaps be related to #122

**Comment by jonklein** [comment]
If I’m not mistaken, this is due to "2000-02-31” not being a valid date (Feb. 31st).  Trying the same thing with Feb. 29th works:

```
>>> cal.parseDT(datetimeString='2000-02-31')
(datetime.datetime(2016, 8, 24, 14, 10, 12), 0)
>>> cal.parseDT(datetimeString='2000-02-29')
(datetime.datetime(2000, 2, 29, 14, 10, 15), 1)
```

**Comment by jonklein** [comment]
Going to close this out - please reopen with another example if there’s still an issue here.
