### ISSUE TITLE
Switch to CircleCI from Travis

### ISSUE THREAD

**Issue by bear** [bear/parsedatetime#158]
My day-job is with CircleCI and I would like to use python-twitter to test CircleCI's python environment usage.

Anyone have any concerns about me switching from Travis to Circle?

I'm going to get a PR going for this tonight unless someone strongly objects - thanks

**Comment by idpaterson** [comment]
Sounds like a good idea, just s/python-twitter/parsedatetime/ :)

**Comment by bear** [comment]
haha - doh!  I cut-n-pasted it from my other project - sorry!

**Comment by bear** [comment]
implemented in PR #159

**Comment by bear** [comment]
closing as this is live now
