### ISSUE TITLE
Not able to parse javascript's ISO string format

### ISSUE THREAD

**Issue by SIlver--** [bear/parsedatetime#161]
Using JavaScript's `toISOString()` does not parse correctly. [The method returns a string in simplified extended ISO 8601 format.](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString).

Example of the code,

    >>> import parsedatetime.parsedatetime as pdt
    >>> cal = pdt.Calendar()
    >>> cal.parse('2016-05-07T07:52:00.000Z')
    ((2016, 5, 6, 20, 16, 0, 4, 127, 0), 2)

**Comment by idpaterson** [comment]
Thanks for reporting, this problem has already been identified in #15 and time zones are discussed in #97.

**Comment by SIlver--** [comment]
Yes but if you do 

    cal.parse('2016-05-07 07:52:00.000Z')
    ((2016, 5, 7, 20, 16, 0, 4, 127, 0), 2)

is the result. It's not the timezone that's the issue but the T between the date and time.

**Comment by bear** [comment]
right, we (meaning I) built in only a limited support for ISO 8601 dates so the T and the Z confuse the code. It is something we could probably fix but it would require adding timezone aware code to *everything* so we haven't yet.

this has always been a case where I suggest that people scan the code for TZ aware ISO 8601 dates *before* calling PDT

**Comment by SIlver--** [comment]
Ah sorry :sweat: I [see](https://github.com/bear/parsedatetime/issues/97#issuecomment-115734775) now where you mention it in #97.

**Comment by bear** [comment]
no worries - only those of us who have been dealing with this stuff for years have it all memorized - hell, even I forget most of it now and depend on folks like the amazing @idpaterson to remind me
