### ISSUE TITLE
Wrong date returned when having a date mentioned in the text

### ISSUE THREAD

**Issue by vkalokyri** [bear/parsedatetime#165]
I have the following text: "lunch with Andrew @ Mon Mar 7, 2016" and as a reference date "2016-03-06", and it gives me as output : 2016-03-08 13:00:00. How did it calculate this date?
This bug happens with other cases as well: e.g. "meeting on Tuesday, 3/29" and reference date="2016-03-24", gives as output date: 2016-04-03.

**Comment by idpaterson** [comment]
Interesting, it looks like "Mon Mar 7, 2016" is being treated as "Mar 7, 2016 plus the number of days between the reference date and the next Monday" and similarly, "Tuesday, 3/29" as "3/29 plus the number of days between the reference date and the next Tuesday."

**Comment by jonklein** [comment]
This should be fixed by the above referenced PR - I think it can be closed out.

**Comment by bear** [comment]
closing this as @jonklein has fixed #178
