### ISSUE TITLE
On Python 2.6

### ISSUE THREAD

**Issue by medecau** [bear/parsedatetime#169]
The README says:

> Python 2.7 or greater is required for parsedatetime version 1.0 or greater.

I've seen a few recent commits adding support or fixing errors specific to 2.6.

Should we keep supporting 2.6?

**Comment by bear** [comment]
I've wanted to keep supporting 2.6 as a few larger projects have that as a requirement.

But yea, we should make sure that the docs are accurate.

**Comment by medecau** [comment]
Keeping the docs up to date would be nice.
More importantly I think is to run tests on python 2.6.
I'm not familiar with with the CI tools currently being used on this repo.
I don't see travis-ci checks. Last build on travis is 5 months old. So I'm not sure where to look.

**Comment by bear** [comment]
If you have the spots where the docs are wrong fresh in your brain please do make a PR or I'll take a look later.

The CI tool used is CircleCI, which I switched to because I now work for them :)

I left the `.travis.yml` in by mistake, i'll remove it after updating `circle.yml` for 2.6

**Comment by bear** [comment]
k, updating the CircleCI environment to run tests using tox so we are testing under 2.6, 2.7, 3.5 and pypy now

Also updated README with new information about tox and versions being tested
