### ISSUE TITLE
release v2.2

### ISSUE THREAD

**Issue by bear** [bear/parsedatetime#177]
The following issues have been resolved since v2.1

PR #180 -- Fixed override of the long time format for Australian locale
Issue #178 -- fix date interpretation when day is also provided
Issue #176 -- fix "some duration before noon/dinner/etc"
Issue #175 -- update code example in readme
Issue #174 -- fix "ass" being interpreted as a time
Issue #169 -- On Python 2.6
Issue #147 -- examples/README refers to nonexistent (deleted?) file
Issue #158 -- Switch to CircleCI from Travis
Issue #161 -- Not able to parse javascript's ISO string format

cc @idpaterson @philiptzou (if they have any reason for me to not do this soon)

**Comment by idpaterson** [comment]
I added a couple to the list. GitHub milestones make assignment and progress tracking of releases cleaner and more public, so I assigned all of these to [2.2](https://github.com/bear/parsedatetime/milestone/1?closed=1) and started 3.0 as well.

**Comment by bear** [comment]
I just accidentally released 2.2 (silly me thought I was in another project!)

Seeing the list above, I'm just going to leave it out there and bump the version

**Comment by idpaterson** [comment]
Sounds good, I'm hoping to come back to continue on 3.0 soon!
