### ISSUE TITLE
French locale

### ISSUE THREAD

**Issue by PaulRenvoise** [bear/parsedatetime#185]
Hi,

I'm currently trying to add French support to your awesome library, but I'm not sure about the current state of this locale. It seems to have some support (cf: https://github.com/bear/parsedatetime/blob/master/tests/TestLocaleBase.py) but only through pyICU it seems, I'm not really sure. Can you confirm ?

**Comment by idpaterson** [comment]
I think that PyICU and especially ICU itself is kind of a pain to install and does not contain as much information as the pdt locales, so very glad to see that you are working on this! For example, taking a look at [French in ICU](http://www.localeplanet.com/icu/fr/) you can see things like decimal separators, weekday and month names, abbreviations, meridian. As by now you have probably discovered the locale metadata specific to parsedatetime like number names, units, next/last modifiers are not provided by ICU. 

What ICU does handle well are well-formatted absolute dates and some of the regional intricacies thereof. For example, [Canadian French](http://www.localeplanet.com/icu/fr-CA/) uses a different date format than [Paris French](http://www.localeplanet.com/icu/fr-FR/). However, ICU does not capture every nuance. In Canada you will see all three mm/dd/yyyy, dd/mm/yyyy, yyyy/mm/dd formats used depending on language and context.

The primary use case where ICU makes sense is if a developer needs to process text in various source locales and that processing will be done from a centralized system on which ICU could be installed. I walked one of my Japanese users through ICU setup in the past and after some aggravation it was working, but not providing much benefit in the area of natural language date processing that parsedatetime (and by extension my own project) was known for.

**Comment by PaulRenvoise** [comment]
Thanks @idpaterson for the explanation about ICU!

Closing this issue as the PR #200 add the french locale.
