### ISSUE TITLE
Fixing __init__.py so can build from pip

### ISSUE THREAD

**Issue by phoebebright** [bear/parsedatetime#211]
If I build a fork from pip, I get the error:

      RuntimeError: Unable to find __email__ string.

I've fixed this in my fork by adding this in parsedatetime/__init__.py

      __email__ = 'bear@bear.im'
      __url__ = 'https://github.com/bear/parsedatetime'
      __download_url__ = 'https://github.com/bear/parsedatetime'
      __description__ = 'Parse human-readable date/time strings'

Not sure if this is the right info but it fixes the error.

**Comment by bear** [comment]
I am seeing this already in place - see https://github.com/bear/parsedatetime/blob/master/parsedatetime/__init__.py#L44

going to mark as not a bug
