### ISSUE TITLE
Nächster Donnerstag, Fail !!!

### ISSUE THREAD

**Issue by Arsaev** [bear/parsedatetime#218]
when i try to get next Thursday date with German language request it returns now() with status code 0.
 
request text Nächster Donnerstag(Naechster Donnerstag)

**Comment by idpaterson** [comment]
This is related to #102 if you don't mind adding a response to that issue. I was trying to improve the German locale based on some suggestions that came in but I ran into a few deeper issues with getting any of the customizations to work. Any examples that you can provide of common date phrases (and any alternate conjugations) that do not work properly would be helpful.
