### ISSUE TITLE
Abuse of `setup_requires` for the non-runtime dependency `pytest-runner`

### ISSUE THREAD

**Issue by ankostis** [bear/parsedatetime#219]
The `setup.py` script has as a setup requirement a test-time one, `pytest-runner`.
According to [the docs](https://pip.readthedocs.io/en/1.4.1/cookbook.html#controlling-setup-requires), `setup_requires` is for dependencies of the setup-tools themselves.

Such requirements typically are placed in the `tests_require` argument.
If this is currently impossible due to some installation script, there is additionally the `test_suite` argument for facilitating the launching of tests.

Thank you for your time.

**Comment by bear** [comment]
PR has been merged
