### ISSUE TITLE
sourceTime in v1.1.2

### ISSUE THREAD

**Issue by seanttierney** [bear/parsedatetime#27]
From the docs, it seems that the sourceTime kwarg gives the user the ability to set the time from which datetimeString will be calculated. I'm looking to calculate relative dates from a historical perspective.

my goal is to get something like this:
    for everyday in days_between_date1_and_date2:
        database.get_stuff(value>today,value<tomorrow)           

So the for the dates between date1 and date2, I need to calculate the value of 'today','yesterday','tomorrow', etc.

    >>> import parsedatetime as pdt; 
    >>> c = pdt.Constants();p = pdt.Calendar(c)
    >>> _from = p.parse('yesterday')[0] #get the sruct_time obj
    >>> _today,parsed = p.parse('today',sourceTime=_from) #no errors are raised, see Lines 1311-1317
    >>> parsed  #0 means we were unable to parse 
    0

Do I misunderstand the purpose of the sourceTime kwarg, am I give it bad data as sourceTime, or is there something else I'm missing.

Thanks.

**Comment by bear** [comment]
First let me apologize for letting this sit for so long - the recent work to the code fixed a lot of little things that was preventing this from working.

You can do the following to tell the code what date to use as the starting point for relative texts:

start  = datetime.datetime(2000, 1, 20, 12, 0, 0).timetuple()
print cal.parse('tomorrow', start)
print cal.parse('yesterday', start)

the above generates:

(time.struct_time(tm_year=2000, tm_mon=1, tm_mday=21, tm_hour=9, tm_min=0, tm_sec=0, tm_wday=4, tm_yday=21, tm_isdst=-1), 1)
(time.struct_time(tm_year=2000, tm_mon=1, tm_mday=19, tm_hour=9, tm_min=0, tm_sec=0, tm_wday=2, tm_yday=19, tm_isdst=-1), 1)

marking as resolved
