### ISSUE TITLE
parse returns tuple with a return code of 3

### ISSUE THREAD

**Issue by bhairav13** [bear/parsedatetime#29]
Great module! Haven't found anything similar yet ...

Seeing the issue below with v1.1.2:

import parsedatetime.parsedatetime as pdt
c = pdt.Calendar()
c.parse("tomorrow 0800")
((2013, 11, 4, 8, 0, 0, 0, 308, -1), 3)

Thanks.

**Comment by bear** [comment]
marking this as closed - the return of the parse function was written for a very specific reason and it's now bound to that pattern for all the usual reasons of why legacy api's never change :/
