### ISSUE TITLE
Inconsistent results with '3 months before 12/31'

### ISSUE THREAD

**Issue by klenwell** [bear/parsedatetime#51]
Sometimes it returns `datetime.date(2014, 9, 30)` and sometimes `datetime.date(2014, 12, 31)` -- although results are consistent within a script.

Here's my script:

    import parsedatetime as pdt
    from datetime import date
    from time import mktime
    
    
    def natural_date(human_readable):
        human_readable = human_readable.lower()
    
        # Flag to cause parsedatetime to never go forward
        # http://stackoverflow.com/a/25098991/1093087
        ptc = pdt.Constants()
        ptc.YearParseStyle = 0
        cal = pdt.Calendar(ptc)
    
        result, parsed_as = cal.parse(human_readable)
    
        if not parsed_as:
            raise ValueError("Unable to parse %s" % (human_readable))
    
        return date.fromtimestamp(mktime(result))
    
    #
    # Produce bug
    #
    human_readable = '3 months before 12/31'
    
    results = {}
    
    for n in range(10):
        result = natural_date(human_readable)
        results[result] = (result in results) and results[result] + 1 or 0
    
    print(pdt.__version__)
    print(results)

Here's what I see:

    klenwell@ubuntu1204:~$ .venv-3.4.1/bin/python sandbox/nldp_bug.py 
    1.4
    {datetime.date(2014, 9, 30): 9}
    klenwell@ubuntu1204:~$ .venv-3.4.1/bin/python sandbox/nldp_bug.py 
    1.4
    {datetime.date(2014, 9, 30): 9}
    klenwell@ubuntu1204:~$ .venv-3.4.1/bin/python sandbox/nldp_bug.py 
    1.4
    {datetime.date(2014, 9, 30): 9}      # <---- Compare this
    klenwell@ubuntu1204:~$ .venv-3.4.1/bin/python sandbox/nldp_bug.py 
    1.4
    {datetime.date(2014, 12, 31): 9}     # <---- And this

**Comment by bear** [comment]
With the latest bug fixes that were made for modifiers and number parsing, I think this is now resolved.

I'm closing the issue - please do re-open it if you find that your code is hitting the bug.

thanks!
