### ISSUE TITLE
nlp and parse return different results for date string.

### ISSUE THREAD

**Issue by Rob1080** [bear/parsedatetime#70]
When parsing dates in a form that parsedatetime doesn't expect for the local e.g. YYYY/MM/dd and using en_us locale, then nlp and parse return different results.

For example
```
parse_result = p.parse("2015/10/25", datetime.datetime(2014,9,24,12).timetuple())
#parse_result returns 0 
#(time.struct_time(tm_year=2014, tm_mon=11, tm_mday=16, tm_hour=12, tm_min=41, tm_sec=14, tm_wday=6, tm_yday=320, tm_isdst=0), 0)

nlp_result = p.nlp("2015/10/25", datetime.datetime(2014,9,24,12).timetuple()))
#nlp_result returns 2 dates, one set to 2014-9-24 20:15 and another with date set to 2014/10/25
#((datetime.datetime(2014, 9, 24, 20, 15), 2, 0, 4, '2015'), (datetime.datetime(2014, 10, 25, 12, 0), 1, 5, 10, '10/25'))
```

I'd expect both to return no result. Alternatively, could we be smarter in how parse and nlp work with regard to processing dates in the form yyyy/mm/dd ?
The usecase is that some users (regardless of locale) may choose to use yyyy/mm/dd or their standard locale syntax. Provided the year is 4 characters long, we could parse the date in format yyyy/mm/dd. Are there more gotchas that I'm not aware of?

Thanks
Rob

**Comment by bear** [comment]
marking this as closed and tagging it as a question for others to find
