### ISSUE TITLE
parse returns default time of 0900 with dates like 'next friday' despite passed struct_time

### ISSUE THREAD

**Issue by thomcaldwell** [bear/parsedatetime#81]
I’m passing a date like: next wednesday
parse returns the proper date, but a time of 9:00 am
passing a struct_time with a time set to 00:01 returns the same 9:00 am time
For other date formats, however, the passed struct_time has the intended effect.
Here is my testing.

Here is the behavior without the struct_time
p.parse('next wednesday')
(time.struct_time(tm_year=2015, tm_mon=2, tm_mday=18, tm_hour=9, tm_min=0, tm_sec=0, tm_wday=2, tm_yday=49, tm_isdst=-1), 1)

Now I’ll add the time.struct_time
t_s = time.struct_time(time.localtime()[:3] + (0,0,0,0,0,-1))
t_s
time.struct_time(tm_year=2015, tm_mon=2, tm_mday=12, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=0, tm_yday=0, tm_isdst=-1)
But, the parsed date still returns as 9am
p.parse('next wednesday',t_s)
(time.struct_time(tm_year=2015, tm_mon=2, tm_mday=21, tm_hour=9, tm_min=0, tm_sec=0, tm_wday=5, tm_yday=52, tm_isdst=-1), 1)

Other date formats will work
p.parse('July 1, 2005',t_s)
((2005, 7, 1, 0, 0, 0, 0, 0, -1), 1)
p.parse('July 1',t_s)
((2015, 7, 1, 0, 0, 0, 0, 0, -1), 1)

But when I want to get the effect with a more vague date, the passed struct_time doesn’t seem to have the effect.
p.parse('today',t_s)
(time.struct_time(tm_year=2015, tm_mon=2, tm_mday=12, tm_hour=9, tm_min=0, tm_sec=0, tm_wday=3, tm_yday=43, tm_isdst=-1), 1)
p.parse('today+ 5 days',t_s)
(time.struct_time(tm_year=2015, tm_mon=2, tm_mday=17, tm_hour=9, tm_min=0, tm_sec=0, tm_wday=1, tm_yday=48, tm_isdst=-1), 1)

So it appears that passing the struct_time works for all but the dates in the form
	next wed
	tomorrow
	etc.

**Comment by bear** [comment]
I added a new flag to the Constant() class

cal.ptc.StartTimeFromSourceTime

which defaults to False (for the current behaviour) and when set to True will cause any of the parsing code that used to have 9am hardcoded to now use the hour, minute and second from the given source time.

**Comment by thomcaldwell** [comment]
Thanks.  It works as you say, and as I needed.

**Comment by bear** [comment]
glad I could fix it for you
