### ISSUE TITLE
'last week' and 'next week' are broken

### ISSUE THREAD

**Issue by wychen** [bear/parsedatetime#82]
It can also be reproducible when uncommenting the two lines in TestSimpleOffsets.py.

**Comment by idpaterson** [comment]
I noticed this as well, for example "next month" does not work so I had to convert "next" to "in 1" which parses correctly. I am not sure whether this affects other locales.

**Comment by philiptzou** [comment]
I think this one has been fixed already:

https://github.com/bear/parsedatetime/commit/7e90d4f27f1a39c41069081c0115bcd416c94674#diff-4ba4000a0afe0dfa34985dbcc9d6958dR111

**Comment by wychen** [comment]
Thanks for fixing it, Philip!
