### ISSUE TITLE
Afternoon?

### ISSUE THREAD

**Issue by wardellchandler** [bear/parsedatetime#84]
"Afternoon" defaults to 12pm, which of course isn't noon when using the parse or nlp functions.
"Tomorrow afternoon" defaults to 12pm the next day when using the parse function.
"Tomorrow afternoon" defaults to 9am the next day when using the nlp function.

I expected these to default to 3pm the current day, and 3pm the next day respectively. (Or a comparable time that is distinctly after noon.) Morning, noon, and evening all work as expected.

**Comment by bear** [comment]
nice find - I have never noticed (or run into) this

thanks!

**Comment by bear** [comment]
fixed by @philiptzou
