### ISSUE TITLE
Inconsistencies / inaccuracies with '-1 day_of_week' and other date conversions

### ISSUE THREAD

**Issue by johnnyutahh** [bear/parsedatetime#88]
Details here:
https://gist.github.com/johnnyutahh/24f9a48a331fd36a4e97#comment-1453139

**Comment by bear** [comment]
All of these should be working now except for those that are +/- # format, like

-1 sunday
The reason for that is that the -1 is a modifier for a default unit of the phrase that follows but not a next/last modifier - so it will determine the date for "sunday" and then adjust it by a single day.

marking this as closed
