### ISSUE TITLE
New PyPI release?

### ISSUE THREAD

**Issue by philiptzou** [bear/parsedatetime#91]
@bear it has been a long while since [version 1.4](https://pypi.python.org/pypi/parsedatetime/). Would you like to release a new version on PyPI? Or you can grant me the privileges to update the package (my username is Philip_Tzou on PyPI).

**Comment by bear** [comment]
I will do this very soon

**Comment by philiptzou** [comment]
@bear Wonderful!

**Comment by bear** [comment]
ok, wasn't "very soon" ... but v1.5 is now available

@philiptzou I've added you to PyPI as a Maintainer role so we can make future updates more timely - thanks!

**Comment by philiptzou** [comment]
@bear Cool!
