### ISSUE TITLE
Incorrect parsing of last month

### ISSUE THREAD

**Issue by AgDude** [bear/parsedatetime#95]
For example "last april 1" or "last april first" I expect to get 2015/4/1, but instead am getting 2016/4/1.

**Comment by idpaterson** [comment]
I took a look but this one is a bit beyond me. The phrase gets passed into `_evalModifier` which doesn't know how to handle this format. I haven't fully traced the logic through to see where it ultimately fails, but I would love to see support for this! 

As a side note, don't be fooled by "next april 1" which *seems* to work. Try "next april 5" and you'll see it doesn't do the right thing – the number is ignored and you always get the following April 1.

**Comment by bear** [comment]
I've always wanted to make the handling of the modifier (next, last, etc) be delayed until after the phrase after it has been fully evaluated for partial date/time 's - then it would be applied to the portion that was missing allowing "next april 5" to be handled as ("next" ("april 5")) and it would increment the year.

but that doesn't help solve the bug, just me being all chatty about old code :/

**Comment by bear** [comment]
@idpaterson I created pull request #98 as a possible fix for this but I would like your (and the others) opinion on if it's the best fix.

Also, need to figure out how to get the named tuple that it generates back into the normal tuple that parse() returns

**Comment by bear** [comment]
fixed in v1.5
