### ISSUE TITLE
Incorrect result when using both sourceTime and tzinfo

### ISSUE THREAD

**Issue by AgDude** [bear/parsedatetime#97]
Consider this example:

```
In [17]: cal = parsedatetime.Calendar()

In [18]: earlier, earlier.tzinfo
Out[18]: (datetime.datetime(2015, 6, 11, 13, 42, 27, 110402, tzinfo=<UTC>), <UTC>)

In [19]: cal.parseDT('now', sourceTime=earlier, tzinfo=timezone.get_current_timezone())
Out[19]:  (datetime.datetime(2015, 6, 11, 13, 42, 27, tzinfo=<DstTzInfo 'America/Chicago' CDT-1 day, 19:00:00 DST>),
 2)

In [20]: make_local(earlier)
Out[20]: datetime.datetime(2015, 6, 11, 8, 42, 27, 110402, tzinfo=<DstTzInfo 'America/Chicago' CDT-1 day, 19:00:00 DST>)
```

You can see that parseDT returns the same time of day as the sourceTime, but replaces the timezone, resulting in a different point in time. In this case I would expect either 13:42 UTC, or 8:42 CDT.

**Comment by AgDude** [comment]
I have not studied the source to find where this is coming from, but this only seems to be a problem with exit code of 2 and relative times. Absolute times like '10AM' work as expected.

**Comment by MatthiasKauer** [comment]
I'm experimenting with something similar. Is make_local your own function? parsedatetime and pytz don't seem to have it.

**Comment by AgDude** [comment]
yes, that is a custom function. It is a wrapper around django timezone util that looks like this: `timezone.localtime(dtm, timezone.get_current_timezone())`

**Comment by bear** [comment]
yes, technically this isn't a bug (well with parsedatetime ;)

parsedatetime isn't supposed to be TZ aware or care - that is up to the calling code to know.
