### ISSUE TITLE
Which year is implied when given just a month and day? Next and last?

### ISSUE THREAD

**Issue by idpaterson** [bear/parsedatetime#99]
There may have already been a discussion about this but I was a bit curious about how the year should be determined when given only a month and a day. This may be an interesting discussion topic for all users even if you're not familiar with the code.

For instance, let's say that today, June 12, 2015 I make a reference to June 10. I'm probably talking about two days ago but parsedatetime assumes I'm looking ahead to 2016.

### Current behavior

Given the source date **June 12, 2015**, parsedatetime will produce the following dates when parsing the text shown in gray:
* `June 11`: June 11, 2016
* `June 12`: June 12, 2015
* `June 13`: June 13, 2015
* `next June 11`: June 11, 2017
* `next June 12`: June 12, 2016
* `next June 13`: June 13, 2016
* `last June 11`: June 11, 2015
* `last June 12`: June 12, 2014
* `last June 13`: June 13, 2014

The logic considers the 365±1 day period beginning today to be my frame of reference. It's not *wrong* since the behavior can be documented and understood easily, but it may not be expected.

### What is expected?

Given the source date **June 12, 2015**, I think that the following would be expected:
* `June 11`: June 11, 2015
* `June 12`: June 12, 2015
* `June 13`: June 13, 2015
* `next June 11`: June 11, 2016
* `next June 12`: June 12, 2016
* `next June 13`: June 13, 2016
* `last June 11`: June 11, 2014
* `last June 12`: June 12, 2014
* `last June 13`: June 13, 2014

This logic considers the current Jan 1–Dec 31 period to be my frame of reference. "Next" means the date is in the upcoming year, "last" means the date is in the preceding year, and the omission of both suggests that the date is in the current year.

#### End of the year

The example above is oversimplified as it considers only today, tomorrow, and yesterday. I don't think it's necessarily as simple as requiring "next" to refer to dates in the following year. If today is December 28 and I want to refer to January 4, I would probably not say *next January 4*; it's just a couple days away. 

Any good ideas for how to handle that? For example, if the date is within ±90 days of today then use it regardless of the year, otherwise assume the date is in the current year. I am afraid that crossing over the new year like that would be more error prone and difficult to understand. There is a fine line here between striving for the most likely natural language interpretation and employing logic that is stable and easy to understand.

### Other considerations

* If we agree that the current implementation is unexpected, how much work would it be to change the frame of reference like this?
* Which other phrases would this change affect? For example:
    * `June`: June, 2015 rather than June, 2016
    * `next May`: May, 2016 rather than May, 2017
* Would this badly affect backwards compatibility for your particular use case? This would probably require a major version update.

**Comment by bear** [comment]
That behaviour is done for reason - the first use case for parsedatetime was to allow phrases in the Chandler project's calendar input. The vast majority of dates entered for that use case are future.

But you also need to know that this is already considered by the code - there is a set of flags that alter how next/last work with missing values - see https://github.com/bear/parsedatetime/blob/master/parsedatetime/__init__.py#L2140 for the one that covers a year value.

YearParseStyle, DOWParseStyle and CurrentDOWParseStyle

An example of usage can be found https://github.com/bear/parsedatetime/blob/master/parsedatetime/tests/TestFrenchLocale.py#L71

**Comment by idpaterson** [comment]
Oh, that's excellent! I had not taken a close enough look at `Constants` to discover the existing ability to configure this exactly how I described above.

So to wrap this up for anyone desiring to tweak this behavior, here is an example setup for parsing past and future dates relative to the current calendar year:
```python
import parsedatetime as pdt
con = pdt.Constants()

# When a year is not specified, assume the current year regardless
# of whether the date is before or after today
con.YearParseStyle = 0

# When given a day of week that is earlier than today 
# (e.g. *Monday* when today is Tuesday), assume that day 
# refers to the current week rather than the following week.
con.DOWParseStyle = 0

# When given a day of week matching today, parse as today's 
# date rather than one week later.
con.CurrentDOWParseStyle = 0

cal = pdt.Calendar(con)

cal.parse(...)
```
The source code has more complete documentation for those options; each supports `1` (the default), `0`, and `-1`. In general, use cases where future dates are entered will prefer the default option while other cases may prefer `0`. There are probably some specialized use cases for `-1` but that one is probably less common.
